### ISSUE TITLE
proxy好像有问题

### ISSUE THREAD

**Issue by J3n5en** [reruin/nrop#1]
proxy好像有问题，用服务器转发会使整个node线程挂掉

**Comment by J3n5en** [comment]
#2 
关联一下pr。。。应该可以解决这个bug。

**Comment by reruin** [comment]
headers 还是要取的，里面有duration-range 这类信息支持断点续传。直接pipe视频不能拖拽。
http.head 里少加了 {method:method}

**Comment by J3n5en** [comment]
好的，那你看看怎么解决，，等着看片呢。。。

**Comment by J3n5en** [comment]
啊，，我知道了，好像不是挂掉了，，只是有点慢罢了。。。好像太大问题。。。关了

**Comment by reruin** [comment]
更新了下，顺便增加了个 moc.sodeivx
